# Generated by Django 5.0.6 on 2026-06-25 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales'), ('KAM', 'KAM')], default='SALES', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('specifier', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Review', 'Under Review'), ('Revised', 'Revised')], default='Active', max_length=20)),
                ('icon', models.CharField(choices=[('file', 'file'), ('spreadsheet', 'spreadsheet'), ('presentation', 'presentation'), ('image', 'image'), ('csv', 'csv')], default='file', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('employee', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('request_details', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processed', 'Processed')], default='Pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='api.document')),
            ],
            options={
                'db_table': 'modification_requests',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReadAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_requests', to='api.document')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'read_access_requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
